console.log("Parth")
console.log("Parth")
console.log("Parth")
console.log("Parth")
console.log("Parth")
console.log("Parth")
console.log("Parth")
console.log("Parth")
console.log("Parth")
console.log("parth parth parth")